streets_nats_bridge:
  streets_parameters:
    KAFKA_BROKER_IP: "localhost" #change to carma-streets ipv4 address
    KAFKA_BROKER_PORT: "9092"
    NATS_IP: "192.168.1.169" #change to amazon ec2 ipv4 address
    NATS_PORT: "4222"
    UNIT_ID: "streets_id"
    UNIT_TYPE: "infrastructure"
    LOG_LEVEL: "debug"
    LOG_NAME: "streets_nats_bridge"
    LOG_PATH: "/var/logs/" 
    LOG_ROTATION_SIZE_BYTES: "2147483648" #2 gigabytes
    KAFKA_CONSUMER_RESET: "earliest" 
    KAFKA_CONSUMER_GROUP: "my-group"